spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssi
    username: ssi
    password: ssi
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
